name: Deploy to Vercel

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

permissions:
  contents: write
  pull-requests: read

jobs:
  # Job to run checks on develop branch
  check:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Build project
        run: npm run build

  # Job to merge develop to main and trigger deployment
  merge-and-deploy:
    needs: check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Merge develop to main
        run: |
          git fetch origin
          git checkout main
          git merge origin/develop --no-ff -m "Auto-merge develop to main"
          git push origin main
          
